### ISSUE TITLE
Build failed with UglifyJS

### ISSUE THREAD

**Issue by huygn** [vkbansal/react-notie#2]
Hi, nice small & useful component, I got error when using `create-react-app 0.8.4` and run `build`:

```
❯ yarn build
yarn build v0.22.0
$ react-scripts build
Creating an optimized production build...
Failed to compile.

static/js/main.d6ba331e.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [./~/react-notie/modules/Notie.js:174,47]

error Command failed with exit code 1.
```

**Comment by vkbansal** [comment]
Can you post your build scripts and settings? Specially babel and webpack.

**Comment by huygn** [comment]
I use https://github.com/facebookincubator/create-react-app, this is their build script: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/build.js

Their babel configs: https://github.com/facebookincubator/create-react-app/tree/master/packages/react-scripts/config

**Comment by vkbansal** [comment]
Ok I've found the issue. The issue is caused because UglifyJS does not support es6 yet.

**Comment by kyrisu** [comment]
I've experienced the same problem, a workaround (if you are feeling adventurous) would be to replace the build-in uglifyjs plugin with beta version of `uglifyjs-webpack-plugin` which uses official `uglify-es` that supports es6. 

```
 npm i -D uglifyjs-webpack-plugin@1.0.0-beta.1 uglify-es
```

Then it's just a matter of updating 2 lines in your webpack config file.

**Comment by nicksarafa** [comment]
@vkbansal which two lines should we update to get the library working with create-react-app (most likely where the original issue came from). 

Love the library! Thanks for implementing. Will definitley contribute and get the input notie working

**Comment by vkbansal** [comment]
Most probably https://github.com/vkbansal/react-notie/blob/master/src/Notie.js#L141
