### ISSUE TITLE
exported members not accurate to repo

### ISSUE THREAD

**Issue by tekgiant** [vkbansal/react-notie#6]
`npm install --save react-notie`

Docs say the exported members include NotieProvider, this is not the case. There is a NotieContext which is no where in the docs

Confirmed package name, author, version. Everything checks out, but the files that this repo should be outputting is not what is coming down from npmjs

**Comment by vkbansal** [comment]
Which version is getting installed on `npm install --save react-notie`?

Can you check your `package.json`?

**Comment by tekgiant** [comment]
From the `package.json`: "_resolved": "https://registry.npmjs.org/react-notie/-/react-notie-2.0.0-alpha.5.tgz",  Sorry for the delay in responding

Edit: Looks like when I opened this issue the current version was alpha.3. If I specify that version I can still see the `NotieContext`, but in alpha.5 there is only `Notie` and `NotieLevel`. It appears `withNotie` which is also referenced in your Usage docs is also not part of this package anymore.

**Comment by vkbansal** [comment]
Please do not use alpha versions, specially in production.

**!!Alpha versions can have breaking changes!!**

**Comment by tekgiant** [comment]
Never said I was using it in production. And I didn't specify alpha, it's just what npm dished out by default. Maybe consider not publishing alpha versions if you don't want people using them or change how you publish to npm so that `npm install react-notie` resolves to a stable version. 

Regardless your documentation is several versions out of date, so maybe specify the version the documentation is relevant to if you don't plan on keeping it up to date with the latest published version.

**Comment by vkbansal** [comment]
I have fixed the npm tags. Now on running npm install, you'll get stable
build, whose docs are published.
